// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package test is a generated GoMock package.
package test

import (
	context "context"
	reflect "reflect"

	model "github.com/barashF/lms/service-course/internal/model"
	record "github.com/barashF/lms/service-course/internal/usecase/enrollment/record"
	orders "github.com/barashF/lms/service-course/proto/orders"
	payment "github.com/barashF/lms/service-course/proto/payment"
	profiles "github.com/barashF/lms/service-course/proto/profiles"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockpaymentGateway is a mock of paymentGateway interface.
type MockpaymentGateway struct {
	ctrl     *gomock.Controller
	recorder *MockpaymentGatewayMockRecorder
}

// MockpaymentGatewayMockRecorder is the mock recorder for MockpaymentGateway.
type MockpaymentGatewayMockRecorder struct {
	mock *MockpaymentGateway
}

// NewMockpaymentGateway creates a new mock instance.
func NewMockpaymentGateway(ctrl *gomock.Controller) *MockpaymentGateway {
	mock := &MockpaymentGateway{ctrl: ctrl}
	mock.recorder = &MockpaymentGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpaymentGateway) EXPECT() *MockpaymentGatewayMockRecorder {
	return m.recorder
}

// GetPaymentByOrderID mocks base method.
func (m *MockpaymentGateway) GetPaymentByOrderID(arg0 context.Context, arg1 uuid.UUID) (*payment.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentByOrderID", arg0, arg1)
	ret0, _ := ret[0].(*payment.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPaymentByOrderID indicates an expected call of GetPaymentByOrderID.
func (mr *MockpaymentGatewayMockRecorder) GetPaymentByOrderID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentByOrderID", reflect.TypeOf((*MockpaymentGateway)(nil).GetPaymentByOrderID), arg0, arg1)
}

// MockorderGateway is a mock of orderGateway interface.
type MockorderGateway struct {
	ctrl     *gomock.Controller
	recorder *MockorderGatewayMockRecorder
}

// MockorderGatewayMockRecorder is the mock recorder for MockorderGateway.
type MockorderGatewayMockRecorder struct {
	mock *MockorderGateway
}

// NewMockorderGateway creates a new mock instance.
func NewMockorderGateway(ctrl *gomock.Controller) *MockorderGateway {
	mock := &MockorderGateway{ctrl: ctrl}
	mock.recorder = &MockorderGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockorderGateway) EXPECT() *MockorderGatewayMockRecorder {
	return m.recorder
}

// GetOrderByID mocks base method.
func (m *MockorderGateway) GetOrderByID(arg0 context.Context, arg1 uuid.UUID) (*orders.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderByID", arg0, arg1)
	ret0, _ := ret[0].(*orders.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderByID indicates an expected call of GetOrderByID.
func (mr *MockorderGatewayMockRecorder) GetOrderByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByID", reflect.TypeOf((*MockorderGateway)(nil).GetOrderByID), arg0, arg1)
}

// MockprofileGateway is a mock of profileGateway interface.
type MockprofileGateway struct {
	ctrl     *gomock.Controller
	recorder *MockprofileGatewayMockRecorder
}

// MockprofileGatewayMockRecorder is the mock recorder for MockprofileGateway.
type MockprofileGatewayMockRecorder struct {
	mock *MockprofileGateway
}

// NewMockprofileGateway creates a new mock instance.
func NewMockprofileGateway(ctrl *gomock.Controller) *MockprofileGateway {
	mock := &MockprofileGateway{ctrl: ctrl}
	mock.recorder = &MockprofileGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockprofileGateway) EXPECT() *MockprofileGatewayMockRecorder {
	return m.recorder
}

// GetProfileByUserID mocks base method.
func (m *MockprofileGateway) GetProfileByUserID(arg0 context.Context, arg1 uuid.UUID) (*profiles.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfileByUserID", arg0, arg1)
	ret0, _ := ret[0].(*profiles.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfileByUserID indicates an expected call of GetProfileByUserID.
func (mr *MockprofileGatewayMockRecorder) GetProfileByUserID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfileByUserID", reflect.TypeOf((*MockprofileGateway)(nil).GetProfileByUserID), arg0, arg1)
}

// MockenrollmentRepository is a mock of enrollmentRepository interface.
type MockenrollmentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockenrollmentRepositoryMockRecorder
}

// MockenrollmentRepositoryMockRecorder is the mock recorder for MockenrollmentRepository.
type MockenrollmentRepositoryMockRecorder struct {
	mock *MockenrollmentRepository
}

// NewMockenrollmentRepository creates a new mock instance.
func NewMockenrollmentRepository(ctrl *gomock.Controller) *MockenrollmentRepository {
	mock := &MockenrollmentRepository{ctrl: ctrl}
	mock.recorder = &MockenrollmentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockenrollmentRepository) EXPECT() *MockenrollmentRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockenrollmentRepository) Create(arg0 context.Context, arg1 model.Enrollment) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockenrollmentRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockenrollmentRepository)(nil).Create), arg0, arg1)
}

// FetchByCourseIDUserID mocks base method.
func (m *MockenrollmentRepository) FetchByCourseIDUserID(ctx context.Context, courseID, userID uuid.UUID) (*model.Enrollment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByCourseIDUserID", ctx, courseID, userID)
	ret0, _ := ret[0].(*model.Enrollment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByCourseIDUserID indicates an expected call of FetchByCourseIDUserID.
func (mr *MockenrollmentRepositoryMockRecorder) FetchByCourseIDUserID(ctx, courseID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByCourseIDUserID", reflect.TypeOf((*MockenrollmentRepository)(nil).FetchByCourseIDUserID), ctx, courseID, userID)
}

// MockcourseRepository is a mock of courseRepository interface.
type MockcourseRepository struct {
	ctrl     *gomock.Controller
	recorder *MockcourseRepositoryMockRecorder
}

// MockcourseRepositoryMockRecorder is the mock recorder for MockcourseRepository.
type MockcourseRepositoryMockRecorder struct {
	mock *MockcourseRepository
}

// NewMockcourseRepository creates a new mock instance.
func NewMockcourseRepository(ctrl *gomock.Controller) *MockcourseRepository {
	mock := &MockcourseRepository{ctrl: ctrl}
	mock.recorder = &MockcourseRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcourseRepository) EXPECT() *MockcourseRepositoryMockRecorder {
	return m.recorder
}

// FetchByID mocks base method.
func (m *MockcourseRepository) FetchByID(arg0 context.Context, arg1 uuid.UUID) (*model.Course, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByID", arg0, arg1)
	ret0, _ := ret[0].(*model.Course)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByID indicates an expected call of FetchByID.
func (mr *MockcourseRepositoryMockRecorder) FetchByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByID", reflect.TypeOf((*MockcourseRepository)(nil).FetchByID), arg0, arg1)
}

// MockEnrollmentStrategy is a mock of EnrollmentStrategy interface.
type MockEnrollmentStrategy struct {
	ctrl     *gomock.Controller
	recorder *MockEnrollmentStrategyMockRecorder
}

// MockEnrollmentStrategyMockRecorder is the mock recorder for MockEnrollmentStrategy.
type MockEnrollmentStrategyMockRecorder struct {
	mock *MockEnrollmentStrategy
}

// NewMockEnrollmentStrategy creates a new mock instance.
func NewMockEnrollmentStrategy(ctrl *gomock.Controller) *MockEnrollmentStrategy {
	mock := &MockEnrollmentStrategy{ctrl: ctrl}
	mock.recorder = &MockEnrollmentStrategyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnrollmentStrategy) EXPECT() *MockEnrollmentStrategyMockRecorder {
	return m.recorder
}

// CanEnroll mocks base method.
func (m *MockEnrollmentStrategy) CanEnroll(ctx context.Context, course *model.Course, userID, orderID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanEnroll", ctx, course, userID, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CanEnroll indicates an expected call of CanEnroll.
func (mr *MockEnrollmentStrategyMockRecorder) CanEnroll(ctx, course, userID, orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanEnroll", reflect.TypeOf((*MockEnrollmentStrategy)(nil).CanEnroll), ctx, course, userID, orderID)
}

// MockPaymentChecker is a mock of PaymentChecker interface.
type MockPaymentChecker struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentCheckerMockRecorder
}

// MockPaymentCheckerMockRecorder is the mock recorder for MockPaymentChecker.
type MockPaymentCheckerMockRecorder struct {
	mock *MockPaymentChecker
}

// NewMockPaymentChecker creates a new mock instance.
func NewMockPaymentChecker(ctrl *gomock.Controller) *MockPaymentChecker {
	mock := &MockPaymentChecker{ctrl: ctrl}
	mock.recorder = &MockPaymentCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentChecker) EXPECT() *MockPaymentCheckerMockRecorder {
	return m.recorder
}

// CheckPayment mocks base method.
func (m *MockPaymentChecker) CheckPayment(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPayment", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckPayment indicates an expected call of CheckPayment.
func (mr *MockPaymentCheckerMockRecorder) CheckPayment(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPayment", reflect.TypeOf((*MockPaymentChecker)(nil).CheckPayment), arg0, arg1)
}

// MockPaymentCheckerFactory is a mock of PaymentCheckerFactory interface.
type MockPaymentCheckerFactory struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentCheckerFactoryMockRecorder
}

// MockPaymentCheckerFactoryMockRecorder is the mock recorder for MockPaymentCheckerFactory.
type MockPaymentCheckerFactoryMockRecorder struct {
	mock *MockPaymentCheckerFactory
}

// NewMockPaymentCheckerFactory creates a new mock instance.
func NewMockPaymentCheckerFactory(ctrl *gomock.Controller) *MockPaymentCheckerFactory {
	mock := &MockPaymentCheckerFactory{ctrl: ctrl}
	mock.recorder = &MockPaymentCheckerFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentCheckerFactory) EXPECT() *MockPaymentCheckerFactoryMockRecorder {
	return m.recorder
}

// GetPaymentChecker mocks base method.
func (m *MockPaymentCheckerFactory) GetPaymentChecker(arg0 int64) record.PaymentChecker {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentChecker", arg0)
	ret0, _ := ret[0].(record.PaymentChecker)
	return ret0
}

// GetPaymentChecker indicates an expected call of GetPaymentChecker.
func (mr *MockPaymentCheckerFactoryMockRecorder) GetPaymentChecker(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentChecker", reflect.TypeOf((*MockPaymentCheckerFactory)(nil).GetPaymentChecker), arg0)
}

// MockEnrollmentFactory is a mock of EnrollmentFactory interface.
type MockEnrollmentFactory struct {
	ctrl     *gomock.Controller
	recorder *MockEnrollmentFactoryMockRecorder
}

// MockEnrollmentFactoryMockRecorder is the mock recorder for MockEnrollmentFactory.
type MockEnrollmentFactoryMockRecorder struct {
	mock *MockEnrollmentFactory
}

// NewMockEnrollmentFactory creates a new mock instance.
func NewMockEnrollmentFactory(ctrl *gomock.Controller) *MockEnrollmentFactory {
	mock := &MockEnrollmentFactory{ctrl: ctrl}
	mock.recorder = &MockEnrollmentFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnrollmentFactory) EXPECT() *MockEnrollmentFactoryMockRecorder {
	return m.recorder
}

// GetStrategy mocks base method.
func (m *MockEnrollmentFactory) GetStrategy(arg0 model.TypeCourse) record.EnrollmentStrategy {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStrategy", arg0)
	ret0, _ := ret[0].(record.EnrollmentStrategy)
	return ret0
}

// GetStrategy indicates an expected call of GetStrategy.
func (mr *MockEnrollmentFactoryMockRecorder) GetStrategy(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStrategy", reflect.TypeOf((*MockEnrollmentFactory)(nil).GetStrategy), arg0)
}
